name: cron-job
on:
  push:
    branches:
      - main  # Chạy khi đẩy mã lên nhánh main
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: every-five-minute
        run: curl -X POST https://bi-cam.vercel.app/api/trigger